
SIGILS_MAPPING = {
    'Made of Stone': 'madeofstone',
    'Rabbit Hole': 'drawrabbits',
    'Bees Within': 'beesonhit',
    'Sprinter': 'strafe',
    'Touch of Death': 'deathtouch',
    'Fledgling': 'evolve',
    'Fledgling (1)': 'evolve_1',
    'Fledgling (2)': 'evolve_2',
    'Fledgling (3)': 'evolve_3',
    'Dam Builder': 'createdams',
    'Hoarder': 'tutor',
    'Burrower': 'whackamole',
    'Fecundity': 'drawcopy',
    'Loose Tail': 'tailonhit',
    'Corpse Eater': 'corpseeater',
    'Bone King': 'quadruplebones',
    'Waterborne': 'submerge',
    'Unkillable': 'drawcopyondeath',
    'Sharp Quills': 'sharp',
    'Hefty': 'strafepush',
    'Rampager': 'strafeswap',
    'Brood Parasite': 'createegg',
    'Armored': 'deathshield',
    'Double Strike': 'doublestrike',
    'Morsel': 'morsel',
    'Blood Lust': 'gainattackonkill',
    'Scavenger': 'opponentbones',
    'Finical Hatchling': 'hydraegg',
    'Ant Spawner': 'drawant',
    'Guardian': 'guarddog',
    'Airborne': 'flying',
    'Many Lives': 'sacrificial',
    'Repulsive': 'preventattack',
    'Worthy Sacrifice': 'tripleblood',
    'Mighty Leap': 'reach',
    'Bifurcated Strike': 'splitstrike',
    'Trifurcated Strike': 'tristrike',
    'Frozen Away': 'icecube',
    'Sinkhole': 'sinkhole',
    'Bone Digger': 'bonedigger',
    'Trinket Bearer': 'randomconsumable',
    'Steel Trap': 'steeltrap',
    'Amorphous': 'randomability',
    'Tidal Lock': 'squirrelorbit',
    'Moon Strike': 'allstrike',
    'Leader': 'buffneighbours',
    'Brittle': 'brittle',
    'Skeleton Crew': 'skeletonstrafe',
    'Green Mox': 'gaingemgreen',
    'Orange Mox': 'gaingemorange',
    'Blue Mox': 'gaingemblue',
    'Gem Animator': 'buffgems',
    'Ruby Heart': 'droprubyondeath',
    'Mental Gemnastics': 'gemsdraw',
    'Gem Dependant': 'gemdependant',
    'Great Mox': 'gaingemtriple',
    'Handy': 'drawnewhand',
    'Squirrel Shedder': 'squirrelstrafe',
    'Attack Conduit': 'conduitbuffattack',
    'Spawn Conduit': 'conduitfactory',
    'Healing Conduit': 'conduitheal',
    'Null Conduit': 'conduitnull',
    'Battery Bearer': 'gainbattery',
    'Detonator': 'explodeondeath',
    'Sniper': 'sniper',
    'Nano Armor': 'deathshield',
    'Overclocked': 'permadeath',
    'Bomb Latch': 'latchexplodeondeath',
    'Brittle Latch': 'latchbrittle',
    'Shield Latch': 'latchdeathshield',
    'Dead Byte': 'filesizedamage',
    'Hostage File': 'deletefile',
    'Transformer': 'transformer',
    'Sentry': 'sentry',
    'Gem Detonator': 'explodegems',
    'Gem Guardian': 'shieldgems',
    'Vessel Printer': 'drawvesselonhit',
    'Energy Conduit': 'conduitenergy',
    'Bomb Spewer': 'bombspawner',
    'Double Death': 'doubledeath',
    'Power Dice': 'activatedrandompowerenergy',
    'Enlarge': 'activatedstatsup',
    'Swapper': 'swapstats',
    'Disentomb': 'activateddrawskeleton',
    'Energy Gun': 'activateddealdamage',
    'Bellist': 'createbells',
    'Annoying': 'buffenemy',
    'Gem Spawn Conduit': 'conduitspawngems',
    'Gift Bearer': 'drawrandomcardondeath',
    'Looter': 'loot',
    'True Scholar': 'activatedsacrificedrawcards',
    'Stimulate': 'activatedstatsupenergy',
    'Marrow Sucker': 'activatedheal',
    'Stinky': 'debuffenemy',
    'Buff When Powered': 'cellbuffself',
    'Gift When Powered': 'celldrawrandomcardondeath',
    'Trifurcated When Powered': 'celltristrike',
    'Bonehorn': 'activatedenergytobones',
    'Clinger': 'movebeside',
    'WaterborneSquid': 'submergesquid',
    'Blood Guzzler': 'bloodguzzler',
    'Haunter': 'haunter',
    'Exploding Corpse': 'explodingcorpse',
    'Apparition': 'bloodymary',
    'Virtual Realist': 'virtualreality',
    'Head of Edaxio': 'edaxiohead',
    'Arms of Edaxio': 'edaxioarms',
    'Legs of Edaxio': 'edaxiolegs',
    'Torso of Edaxio': 'edaxiotorso'
}

SIGIL_POWER_LEVELS = {
    'madeofstone': ,
    'drawrabbits': ,
    'beesonhit': ,
    'strafe': ,
    'deathtouch': ,
    'evolve': ,
    'evolve_1': ,
    'evolve_2': ,
    'evolve_3': ,
    'createdams': ,
    'tutor': ,
    'whackamole': ,
    'drawcopy': ,
    'tailonhit': ,
    'corpseeater': ,
    'quadruplebones': ,
    'submerge': ,
    'drawcopyondeath': ,
    'sharp': ,
    'strafepush': ,
    'strafeswap': ,
    'createegg': ,
    'deathshield': ,
    'doublestrike': ,
    'morsel': ,
    'gainattackonkill': ,
    'opponentbones': ,
    'hydraegg': ,
    'drawant': ,
    'guarddog': ,
    'flying': ,
    'sacrificial': ,
    'preventattack': ,
    'tripleblood': ,
    'reach': ,
    'splitstrike': ,
    'tristrike': ,
    'icecube': ,
    'sinkhole': ,
    'bonedigger': ,
    'randomconsumable': ,
    'steeltrap': ,
    'randomability': ,
    'squirrelorbit': ,
    'allstrike': ,
    'buffneighbours': ,
    'brittle': ,
    'skeletonstrafe': ,
    'gaingemgreen': ,
    'gaingemorange': ,
    'gaingemblue': ,
    'buffgems': ,
    'droprubyondeath': ,
    'gemsdraw': ,
    'gemdependant': ,
    'gaingemtriple': ,
    'drawnewhand': ,
    'squirrelstrafe': ,
    'conduitbuffattack': ,
    'conduitfactory': ,
    'conduitheal': ,
    'conduitnull': ,
    'gainbattery': ,
    'explodeondeath': ,
    'sniper': ,
    'deathshield': ,
    'permadeath': ,
    'latchexplodeondeath': ,
    'latchbrittle': ,
    'latchdeathshield': ,
    'filesizedamage': ,
    'deletefile': ,
    'transformer': ,
    'sentry': ,
    'explodegems': ,
    'shieldgems': ,
    'drawvesselonhit': ,
    'conduitenergy': ,
    'bombspawner': ,
    'doubledeath': ,
    'activatedrandompowerenergy': ,
    'activatedstatsup': ,
    'swapstats': ,
    'activateddrawskeleton': ,
    'activateddealdamage': ,
    'createbells': ,
    'buffenemy': ,
    'conduitspawngems': ,
    'drawrandomcardondeath': ,
    'loot': ,
    'activatedsacrificedrawcards': ,
    'activatedstatsupenergy': ,
    'activatedheal': ,
    'debuffenemy': ,
    'cellbuffself': ,
    'celldrawrandomcardondeath': ,
    'celltristrike': ,
    'activatedenergytobones': ,
    'movebeside': ,
    'submergesquid': ,
    'bloodguzzler': ,
    'haunter': ,
    'explodingcorpse': ,
    'bloodymary': ,
    'virtualreality': ,
    'edaxiohead': ,
    'edaxioarms': ,
    'edaxiolegs': ,
    'edaxiotorso':
}

def read_entries(file_path):
    entries = []
    with open(file_path, 'r') as file:
        lines = file.readlines()
    entry = []
    for line in lines:
        if line.strip().startswith('#'):
            continue
        if not line.strip():
            if entry:
                entries.append(entry)
                entry = []
        else:
            entry.append(line.strip())
    if entry:
        entries.append(entry)
    return entries


def calculate_balance(card_data):
    pass


if __name__ == '__main__':
    card_data = read_entries('Leshy Cards.txt')
    calculate_balance(card_data)




# BALANCING FORMULA
# O RESOURCES = 1 Stat Point
# 1 GEM PLACED = 2 Stat Points
# 2 GEMS PLACED = 5 Stat Points
# 1 BLOOD = 2.5 BONES = 3 ENERGY = 1.5 GEMS PLACED = 3 Stat Points
# 5 BONES = 6 ENERGY = 6 Stat Points
# 2 BLOOD = 3 GEMS PLACED = 8 Stat Points
# 3 BLOOD = 14 Stat Points
# 4 BLOOD = 21 Stat Points
# GEM DEPENDENT = 3 Stat Points
# Stat Points = Power * 2 + Toughness + Power Levels of Abilities +/- 1 (flexibility) + 1 for Rare or Talking cards.